name: date_picker_button
description: "A Well designed datetime picker for Flutter."
version: 0.0.1
repository: https://github.com/poyu0692/date_picker_button


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">0.8.2 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
